name: just_some_tries
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get_it: ^7.6.0
  injectable: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  percent_indicator: ^4.2.3
  injectable_generator: ^2.1.6
  build_runner: ^2.4.5

flutter:
  uses-material-design: true

  assets:
    - assets/languages/